// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Eye-Care-Companion",
    platforms: [
        .iOS("16.6")
    ],
    products: [
        .iOSApplication(
            name: "Eye-Care-Companion",
            targets: ["AppModule"],
            bundleIdentifier: "Akhlak.LearnSathi",
            teamIdentifier: "G35LFCGGKB",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .palette),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "Camera will be used for detect eye blink pattern")
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-xcode-playground-support.git", .branch("main"))
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)